'use client';

import { PageHeader } from './page-header';
import { useEffect, useMemo, useState } from 'react';
import { Activity, CarFront, ClipboardList, Gauge, Route, Users } from 'lucide-react';

type Dashboard = { metrics: Record<string, number | null>; activity: { date: string; value: number }[]; requestStatus: Row[]; tripPurpose: Row[]; requestsByDepartment: Row[]; mostUsedVehicles: Row[]; mostActiveDrivers: Row[] };
type Row = { label: string; value: number };

export function AnalyticsDashboard() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [range, setRange] = useState('30');
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => setLoading(true)); const from = new Date(); from.setDate(from.getDate() - Number(range) + 1); fetch(`/api/analytics/dashboard?from=${from.toISOString()}`, { signal: controller.signal }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.message || 'Unable to load analytics.'); return body as Dashboard; }).then(setData).catch((reason) => { if (reason.name !== 'AbortError') setError(reason.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, [range]);
  const metrics = data?.metrics ?? {}; const cards = [{ label: 'Vehicles', value: metrics.vehicles, icon: CarFront }, { label: 'Available', value: metrics.availableVehicles, icon: CarFront }, { label: 'Requests', value: metrics.requests, icon: ClipboardList }, { label: 'Completed trips', value: metrics.completedTrips, icon: Route }, { label: 'Active drivers', value: metrics.activeDrivers, icon: Users }, { label: 'Distance', value: metrics.distanceTravelled === null || metrics.distanceTravelled === undefined ? '—' : `${Number(metrics.distanceTravelled).toFixed(1)} km`, icon: Gauge }];
  return <><PageHeader title="Dashboard Analytics" description="Live fleet metrics, trips, vehicle requests and operational trends." actions={<select value={range} onChange={(event) => setRange(event.target.value)} aria-label="Analytics date range"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">This year</option></select>} />{error && <div className="master-alert">{error}</div>}<section className="metric-grid">{cards.map(({ label, value, icon: Icon }) => <article className="metric-card" key={label}><div className="metric-icon blue"><Icon size={20} /></div><div><p>{label}</p><strong>{value ?? 0}</strong><small>Recorded in fleet data</small></div></article>)}</section>{loading ? <section className="panel"><p>Loading live analytics…</p></section> : !data ? <section className="panel"><p>Analytics could not be loaded.</p></section> : <section className="dashboard-grid"><Chart title="Request activity" rows={data.activity.map((row) => ({ label: row.date, value: row.value }))} /><Breakdown title="Request status" rows={data.requestStatus} /><Breakdown title="Trip purpose" rows={data.tripPurpose} /><Breakdown title="Requests by department" rows={data.requestsByDepartment} /><Breakdown title="Most-used vehicles" rows={data.mostUsedVehicles} /><Breakdown title="Most-active drivers" rows={data.mostActiveDrivers} /></section>}</>;
}
function Chart({ title, rows }: { title: string; rows: Row[] }) { const max = Math.max(1, ...rows.map((row) => row.value)); return <article className="panel chart-panel"><div className="panel-heading"><div><h2>{title}</h2><p>Real vehicle requests by submission date.</p></div><Activity size={19} /></div>{rows.length ? <div className="chart-placeholder" aria-label={title}>{rows.map((row) => <span key={row.label} title={`${row.label}: ${row.value}`} style={{ height: `${Math.max(3, row.value / max * 100)}%` }} />)}</div> : <p className="empty-compact">No activity exists for this period.</p>}</article>; }
function Breakdown({ title, rows }: { title: string; rows: Row[] }) { const max = useMemo(() => Math.max(1, ...rows.map((row) => row.value)), [rows]); return <article className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>Calculated from authorised fleet records.</p></div></div>{rows.length ? <div className="analytics-list">{rows.slice(0, 8).map((row) => <div key={row.label}><span>{row.label}</span><strong>{row.value}</strong><i style={{ width: `${row.value / max * 100}%` }} /></div>)}</div> : <p className="empty-compact">No data available yet.</p>}</article>; }
