'use client';

import { PageHeader } from './page-header';
import { useEffect, useMemo, useState } from 'react';
import { CarFront, ClipboardList, Gauge, Route, Users, type LucideIcon } from 'lucide-react';

type Row = { label: string; value: number };
type Dashboard = { metrics: Record<string, number | null>; activity: { date: string; value: number }[]; driverActivity: { date: string; value: number }[]; distanceActivity: { date: string; value: number }[]; requestStatus: Row[]; tripPurpose: Row[]; requestsByDepartment: Row[]; mostUsedVehicles: Row[]; mostActiveDrivers: Row[] };
type SpeedData = { threshold: number; trend: { recordedAt: string; speed: number }[]; violations: unknown[] };

export function AnalyticsDashboard({ embedded = false }: { embedded?: boolean }) {
  const [data, setData] = useState<Dashboard | null>(null); const [speed, setSpeed] = useState<SpeedData | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [range, setRange] = useState('30');
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => setLoading(true)); const from = new Date(); from.setDate(from.getDate() - Number(range) + 1); const query = `from=${encodeURIComponent(from.toISOString())}`; Promise.all([fetch(`/api/analytics/dashboard?${query}`, { signal: controller.signal }), fetch(`/api/analytics/speed?${query}&threshold=100`, { signal: controller.signal })]).then(async ([dashboardResponse, speedResponse]) => { const dashboardBody = await dashboardResponse.json(); const speedBody = await speedResponse.json(); if (!dashboardResponse.ok) throw new Error(dashboardBody.message || 'Unable to load analytics.'); if (!speedResponse.ok) throw new Error(speedBody.message || 'Unable to load speed analytics.'); return [dashboardBody as Dashboard, speedBody as SpeedData] as const; }).then(([dashboard, speedData]) => { setData(dashboard); setSpeed(speedData); }).catch((reason) => { if (reason.name !== 'AbortError') setError(reason.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, [range]);
  const metrics = data?.metrics ?? {}; const cards = [{ label: 'Vehicles', value: metrics.vehicles, icon: CarFront }, { label: 'Available', value: metrics.availableVehicles, icon: CarFront }, { label: 'Requests', value: metrics.requests, icon: ClipboardList }, { label: 'Completed trips', value: metrics.completedTrips, icon: Route }, { label: 'Active drivers', value: metrics.activeDrivers, icon: Users }, { label: 'Distance', value: metrics.distanceTravelled === null || metrics.distanceTravelled === undefined ? '—' : `${Number(metrics.distanceTravelled).toFixed(1)} km`, icon: Gauge }];
  const speedRows = (speed?.trend ?? []).slice(-80).map((row) => ({ label: row.recordedAt, value: row.speed }));
  const filters = <select value={range} onChange={(event) => setRange(event.target.value)} aria-label="Analytics date range"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">This year</option></select>;
  return <section className={embedded ? 'dashboard-analytics-embedded' : undefined}>{!embedded && <PageHeader title="Dashboard Analytics" description="Live fleet metrics, trips, vehicle requests and operational trends." actions={filters} />}{embedded && <div className="analytics-embedded-heading"><div><h2>Fleet analytics</h2><p>Live request, driver, distance and safety trends.</p></div>{filters}</div>}{error && <div className="master-alert">{error}</div>}<section className="metric-grid">{cards.map(({ label, value, icon: Icon }) => <article className="metric-card" key={label}><div className="metric-icon blue"><Icon size={20} /></div><div><p>{label}</p><strong>{value ?? 0}</strong><small>Recorded in fleet data</small></div></article>)}</section>{loading ? <section className="panel"><p>Loading live analytics…</p></section> : !data ? <section className="panel"><p>Analytics could not be loaded.</p></section> : <><section className="analytics-chart-grid"><LineChart title="Request activity" description="Vehicle requests submitted each day." rows={data.activity.map((row) => ({ label: row.date, value: row.value }))} icon={ClipboardList} /><LineChart title="Driver activity" description="Request-backed trips started each day." rows={data.driverActivity.map((row) => ({ label: row.date, value: row.value }))} icon={Users} tone="blue" /><LineChart title="Speed and overspeed trend" description={`${speed?.violations.length ?? 0} point(s) above the 100 km/h threshold.`} rows={speedRows} icon={Gauge} tone="red" threshold={speed?.threshold ?? 100} unit="km/h" /><LineChart title="Trip distance trend" description="Recorded journey distance by trip date." rows={data.distanceActivity.map((row) => ({ label: row.date, value: row.value }))} icon={Route} tone="gold" unit="km" /></section><section className="dashboard-grid"><Breakdown title="Request status" rows={data.requestStatus} /><Breakdown title="Trip purpose" rows={data.tripPurpose} /><Breakdown title="Requests by department" rows={data.requestsByDepartment} /><Breakdown title="Most-used vehicles" rows={data.mostUsedVehicles} /><Breakdown title="Most-active drivers" rows={data.mostActiveDrivers} /></section></>}</section>;
}

function LineChart({ title, description, rows, icon: Icon, tone = 'green', threshold, unit = '' }: { title: string; description: string; rows: Row[]; icon: LucideIcon; tone?: 'green' | 'blue' | 'red' | 'gold'; threshold?: number; unit?: string }) { const chart = useMemo(() => chartPoints(rows, threshold), [rows, threshold]); return <article className={`panel line-chart-panel ${tone}`}><div className="panel-heading"><div><h2>{title}</h2><p>{description}</p></div><Icon size={19} /></div>{rows.length ? <><div className="line-chart-summary"><strong>{chart.latest}{unit && ` ${unit}`}</strong><span>{chart.max}{unit && ` ${unit}`} peak</span></div><svg className="line-chart" viewBox="0 0 600 190" role="img" aria-label={`${title}: latest ${chart.latest}${unit}, peak ${chart.max}${unit}`} preserveAspectRatio="none"><path className="line-chart-grid" d="M24 28H584M24 74H584M24 120H584M24 166H584" />{threshold !== undefined && <><path className="line-chart-threshold" d={`M24 ${chart.y(threshold)}H584`} /><text x="580" y={chart.y(threshold) - 5} textAnchor="end">{threshold} {unit}</text></>}<path className="line-chart-area" d={`${chart.path} L584 166 L24 166 Z`} /><path className="line-chart-line" d={chart.path} />{chart.points.map((point) => <circle className="line-chart-node" key={`${point.x}-${point.y}`} cx={point.x} cy={point.y} r="4" tabIndex={0} aria-label={`${shortDate(point.label)}: ${point.value}${unit ? ` ${unit}` : ''}`}><title>{`${shortDate(point.label)}: ${point.value}${unit ? ` ${unit}` : ''}`}</title></circle>)}</svg><footer><span>{shortDate(rows[0].label)}</span><span>{shortDate(rows.at(-1)?.label ?? '')}</span></footer></> : <p className="empty-compact">No chart data exists for this period.</p>}</article>; }
function Breakdown({ title, rows }: { title: string; rows: Row[] }) { const max = useMemo(() => Math.max(1, ...rows.map((row) => row.value)), [rows]); return <article className="panel"><div className="panel-heading"><div><h2>{title}</h2><p>Calculated from authorised fleet records.</p></div></div>{rows.length ? <div className="analytics-list">{rows.slice(0, 8).map((row) => <div key={row.label}><span>{row.label}</span><strong>{row.value}</strong><i style={{ width: `${row.value / max * 100}%` }} /></div>)}</div> : <p className="empty-compact">No data available yet.</p>}</article>; }
function chartPoints(rows: Row[], threshold?: number) { const max = Math.max(1, threshold ?? 0, ...rows.map((row) => row.value)); const minX = 24; const maxX = 584; const minY = 28; const maxY = 166; const divisor = Math.max(1, rows.length - 1); const points = rows.map((row, index) => ({ x: minX + index / divisor * (maxX - minX), y: maxY - row.value / max * (maxY - minY), label: row.label, value: Math.round(row.value * 10) / 10 })); return { points, max: Math.round(max * 10) / 10, latest: Math.round((rows.at(-1)?.value ?? 0) * 10) / 10, path: points.map((point, index) => `${index ? 'L' : 'M'}${point.x} ${point.y}`).join(' '), y: (value: number) => maxY - Math.min(value, max) / max * (maxY - minY) }; }
function shortDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short' }).format(date); }
