'use client';

import { FormEvent, useState } from 'react';
import { PageHeader } from './page-header';

type Message = { role: 'admin' | 'assistant'; text: string; title?: string; table?: { label: string; value: string | number }[]; action?: { label: string; href: string } };
const suggestions = ['What was the last trip?', 'Show pending vehicle requests', 'Which vehicle has the highest usage?', 'Which drivers exceeded the speed limit?', 'Generate a vehicle request report'];

export function FleetAssistant() {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function send(event?: FormEvent, suggested?: string) { event?.preventDefault(); const message = (suggested ?? input).trim(); if (!message || loading) return; setMessages((current) => [...current, { role: 'admin', text: message }]); setInput(''); setLoading(true); setError(''); try { const response = await fetch('/api/ai/assistant', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'The assistant could not answer right now.'); setMessages((current) => [...current, { role: 'assistant', text: payload.data.text, title: payload.data.title, table: payload.data.table, action: payload.data.action }]); } catch (reason) { setError(reason instanceof Error ? reason.message : 'The assistant could not answer right now.'); } finally { setLoading(false); } }
  return <><PageHeader title="Fleet AI Assistant" description="Ask secure, data-backed questions about authorised fleet records." actions={<button className="secondary-action" onClick={() => { setMessages([]); setError(''); }}>Clear chat</button>} /><section className="panel fleet-assistant"><div className="assistant-suggestions">{suggestions.map((question) => <button key={question} onClick={() => void send(undefined, question)} disabled={loading}>{question}</button>)}</div><div className="assistant-messages" aria-live="polite">{messages.length ? messages.map((message, index) => <article key={index} className={`assistant-message ${message.role}`}><strong>{message.role === 'admin' ? 'You' : message.title ?? 'Fleet assistant'}</strong><p>{message.text}</p>{message.table && <div className="assistant-table">{message.table.map((row) => <span key={`${row.label}-${row.value}`}><small>{row.label}</small><b>{row.value}</b></span>)}</div>}{message.action && <a className="assistant-action" href={message.action.href}>{message.action.label}</a>}</article>) : <p className="empty-compact">Ask a suggested question to begin. Answers use only authorised fleet records and controlled analytics.</p>}{loading && <p>Checking fleet records…</p>}</div>{error && <div className="master-alert">{error}</div>}<form onSubmit={(event) => void send(event)} className="assistant-input"><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about requests, trips, vehicles, drivers or speed" maxLength={1000} /><button type="submit" disabled={loading || !input.trim()}>Send</button></form></section></>;
}
