'use client';

import { BarChart3, CarFront, ChevronLeft, ClipboardList, Gauge, Route, Users, Wrench } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from './page-header';

type ReportKind = 'requests' | 'trips' | 'drivers' | 'speed' | 'utilisation' | 'maintenance';
type Row = Record<string, unknown>;
type DisplayRow = Record<string, string | number>;
const reports: { kind: ReportKind; title: string; description: string; icon: typeof ClipboardList; available: boolean }[] = [
  { kind: 'requests', title: 'Vehicle Request Report', description: 'Requests, approval status, destinations and allocations.', icon: ClipboardList, available: true },
  { kind: 'trips', title: 'Trip Report', description: 'Request-backed trips, dates, distance, vehicle and driver.', icon: Route, available: true },
  { kind: 'drivers', title: 'Driver Activity Report', description: 'Driver trip participation and completed-trip counts.', icon: Users, available: true },
  { kind: 'speed', title: 'Speed Violation Report', description: 'Recorded speed-limit events from valid GPS points.', icon: Gauge, available: true },
  { kind: 'utilisation', title: 'Vehicle Utilisation Report', description: 'Most-used vehicles based on completed and active trips.', icon: CarFront, available: true },
  { kind: 'maintenance', title: 'Maintenance Report', description: 'Available when maintenance records are added to the system.', icon: Wrench, available: false },
];

export function VehicleRequestReport() {
  const [selected, setSelected] = useState<ReportKind | null>(null);
  const active = reports.find((report) => report.kind === selected);
  return <>{selected && active ? <ReportDetail report={active} onBack={() => setSelected(null)} /> : <ReportHub onSelect={setSelected} />}</>;
}

function ReportHub({ onSelect }: { onSelect: (kind: ReportKind) => void }) {
  return <><PageHeader title="Reports" description="Choose a live fleet report to review, filter, and export." /><section className="report-hub-grid">{reports.map((report) => { const Icon = report.icon; return <button key={report.kind} className="report-hub-card" disabled={!report.available} onClick={() => onSelect(report.kind)}><span className="report-hub-icon"><Icon size={22} /></span><strong>{report.title}</strong><p>{report.description}</p><small>{report.available ? 'Open report' : 'Not available yet'}</small></button>; })}</section></>;
}

function ReportDetail({ report, onBack }: { report: (typeof reports)[number]; onBack: () => void }) {
  const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [status, setStatus] = useState(''); const [search, setSearch] = useState('');
  const endpoint = useMemo(() => endpointFor(report.kind, status, search), [report.kind, search, status]);
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => setLoading(true)); fetch(endpoint, { signal: controller.signal }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message || 'Unable to load report.'); return payload; }).then((payload) => setRows(normalise(report.kind, payload))).catch((reason) => { if (reason.name !== 'AbortError') setError(reason.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, [endpoint, report.kind]);
  function exportCsv() { const formatted = formatRows(report.kind, rows); if (!formatted.length) return; const keys = Object.keys(formatted[0]); const csv = [keys, ...formatted.map((row) => keys.map((key) => row[key]))].map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `${report.kind}-report.csv`; a.click(); URL.revokeObjectURL(url); }
  return <><PageHeader title={report.title} description={report.description} actions={<div className="report-header-actions"><button className="secondary-action" onClick={onBack}><ChevronLeft size={16} /> All reports</button><button className="secondary-action" onClick={exportCsv} disabled={!rows.length}>Export CSV</button></div>} /><section className="panel"><div className="report-filters"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search report" />{report.kind === 'requests' && <select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="PENDING_APPROVAL">Pending approval</option><option value="APPROVED">Approved</option><option value="ALLOCATED">Allocated</option><option value="COMPLETED">Completed</option><option value="REJECTED">Rejected</option></select>}<span className="report-total">{rows.length} record{rows.length === 1 ? '' : 's'}</span></div>{error && <div className="master-alert">{error}</div>}{loading ? <p>Loading live report…</p> : <ReportTable kind={report.kind} rows={rows} />}</section></>;
}

function endpointFor(kind: ReportKind, status: string, search: string) { const params = new URLSearchParams(); if (status) params.set('status', status); if (search) params.set('search', search); if (kind === 'requests') return `/api/analytics/reports/vehicle-requests?${params}`; if (kind === 'trips' || kind === 'drivers') return '/api/trips'; if (kind === 'speed') return '/api/analytics/speed?threshold=100'; return '/api/analytics/dashboard'; }
function normalise(kind: ReportKind, payload: Record<string, unknown>): Row[] { if (kind === 'requests' || kind === 'trips') return (payload.data as Row[] | undefined) ?? []; if (kind === 'speed') return (payload.violations as Row[] | undefined) ?? []; if (kind === 'drivers') { const trips = (payload.data as { driver: { staffName: string }; status: string }[] | undefined) ?? []; const map = new Map<string, { driver: string; trips: number; completed: number }>(); trips.forEach((trip) => { const row = map.get(trip.driver.staffName) ?? { driver: trip.driver.staffName, trips: 0, completed: 0 }; row.trips++; if (trip.status === 'COMPLETED') row.completed++; map.set(row.driver, row); }); return [...map.values()]; } return (payload.mostUsedVehicles as Row[] | undefined) ?? []; }
function formatRows(kind: ReportKind, rows: Row[]): DisplayRow[] { return rows.map((row): DisplayRow => { if (kind === 'requests') { const allocation = (row.allocations as { vehicle?: { registrationNumber: string }; driver?: { staffName: string } }[] | undefined)?.[0]; return { Request: cell(row.requestNumber), Staff: cell(row.staffName), Department: cell(row.department), Unit: cell(row.unit), Purpose: cell(row.purposeOfTrip), Destination: cell(row.destination), Status: cell(row.status), Vehicle: allocation?.vehicle?.registrationNumber ?? '', Driver: allocation?.driver?.staffName ?? '' }; } if (kind === 'trips') { const vehicle = row.vehicle as { registrationNumber?: string } | undefined; const driver = row.driver as { staffName?: string } | undefined; return { Status: cell(row.status), Vehicle: vehicle?.registrationNumber ?? '', Driver: driver?.staffName ?? '', DistanceKm: cell(row.calculatedDistance), Started: cell(row.startedAt), Ended: cell(row.endedAt) }; } return Object.fromEntries(Object.entries(row).map(([key, value]) => [key, cell(value)])); }); }
function cell(value: unknown): string | number { return typeof value === 'number' ? value : typeof value === 'string' ? value : value === null || value === undefined ? '' : String(value); }
function ReportTable({ kind, rows }: { kind: ReportKind; rows: Row[] }) { const formatted = formatRows(kind, rows); if (!formatted.length) return <div className="master-empty"><BarChart3 size={28} /><h2>No report data</h2><p>No matching live records are available for this report.</p></div>; const columns = Object.keys(formatted[0]); return <div className="report-table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{formatted.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column}>{String(row[column] ?? '—')}</td>)}</tr>)}</tbody></table></div>; }
